# Generated by Django 4.2.3 on 2024-06-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalago', '0002_alter_catalogo_table_alter_estadomensaje_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanidmensaje', models.CharField(max_length=100)),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('json', models.TextField(blank=True, null=True)),
                ('idcontacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacto.contacto')),
                ('idusuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipomensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalago.tipomensaje')),
            ],
            options={
                'db_table': 'Mensaje',
            },
        ),
    ]
