# Generated by Django 4.2.3 on 2024-06-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='textomensaje',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
