# Generated by Django 4.2.3 on 2024-06-04 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalago', '0002_alter_catalogo_table_alter_estadomensaje_table_and_more'),
        ('mensaje', '0002_mensaje_textomensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='textomensaje',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipomensaje',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalago.tipomensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='wanidmensaje',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
