# Generated by Django 4.2.3 on 2024-06-04 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_contacto_table'),
        ('mensaje', '0003_alter_mensaje_textomensaje_alter_mensaje_tipomensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='idcontacto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contacto.contacto'),
        ),
    ]
