# Generated by Django 4.2.3 on 2024-06-07 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacto', '0002_alter_contacto_table'),
        ('catalago', '0002_alter_catalogo_table_alter_estadomensaje_table_and_more'),
        ('mensaje', '0004_alter_mensaje_idcontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='idcontacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacto.contacto'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='idusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipomensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalago.tipomensaje'),
        ),
    ]
