# Generated by Django 4.2.3 on 2024-06-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0011_alter_contacto_table'),
        ('mensaje', '0005_alter_mensaje_idcontacto_alter_mensaje_idusuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='idcontacto',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='idcontacto',
            field=models.ManyToManyField(to='contacto.contacto'),
        ),
    ]
