# Generated by Django 4.2.3 on 2024-06-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0011_alter_contacto_table'),
        ('mensaje', '0006_remove_mensaje_idcontacto_mensaje_idcontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='idcontacto',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='idcontacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacto.contacto'),
        ),
    ]
