# Generated by Django 4.2.3 on 2024-06-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensaje', '0008_rename_idcontacto_mensaje_contacto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mensaje',
            table='mensaje',
        ),
    ]
