# Generated by Django 4.2.3 on 2024-06-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensaje', '0009_alter_mensaje_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('enviado', 'Enviado')], default='recibido', max_length=10),
        ),
    ]
