# Generated by Django 4.2.3 on 2024-06-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensaje', '0012_alter_mensaje_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='estado',
        ),
    ]
