# Generated by Django 4.2.3 on 2024-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensaje', '0013_remove_mensaje_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
