# Generated by Django 4.2.3 on 2024-06-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimedia_id', models.CharField(max_length=255, unique=True)),
                ('archivos', models.FileField(upload_to='media/')),
            ],
        ),
    ]
