# Generated by Django 4.2.3 on 2024-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('formatosalida', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogo',
            },
        ),
        migrations.CreateModel(
            name='EstadoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('formatosalida', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estado_mensaje',
            },
        ),
        migrations.CreateModel(
            name='TipoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('formatosalida', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_mensaje',
            },
        ),
    ]
