# Generated by Django 4.2.3 on 2024-06-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogo',
            table='Catalogo',
        ),
        migrations.AlterModelTable(
            name='estadomensaje',
            table='EstadoMensaje',
        ),
        migrations.AlterModelTable(
            name='tipomensaje',
            table='TipoMensaje',
        ),
    ]
