# Generated by Django 4.2.3 on 2024-07-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalago', '0003_alter_catalogo_table_alter_estadomensaje_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogo',
            table='catalago',
        ),
        migrations.AlterModelTable(
            name='estadomensaje',
            table='estadoMensaje',
        ),
        migrations.AlterModelTable(
            name='tipomensaje',
            table='tipoMensaje',
        ),
    ]
