# Generated by Django 4.2.3 on 2024-06-03 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidopaterno', models.CharField(max_length=100)),
                ('apellidomaterno', models.CharField(max_length=100)),
                ('fecharegistro', models.DateField()),
                ('waid', models.CharField(max_length=100)),
                ('nombreperfil', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
    ]
