# Generated by Django 4.2.3 on 2024-06-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacto',
            table='Contacto',
        ),
    ]
