# Generated by Django 4.2.3 on 2024-06-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_alter_contacto_waid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecharegistro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
