# Generated by Django 4.2.3 on 2024-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0007_alter_contacto_waid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='waid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
