# Generated by Django 4.2.3 on 2024-06-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0009_alter_contacto_waid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellidomaterno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellidopaterno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
