# Generated by Django 4.2.3 on 2024-06-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0010_alter_contacto_apellidomaterno_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacto',
            table='contacto',
        ),
    ]
