# Generated by Django 4.2.3 on 2024-06-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leído'), ('NO_ENCONTRADO', 'No encontrado')], max_length=20)),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensaje.mensaje')),
            ],
            options={
                'db_table': 'Bitacora',
            },
        ),
    ]
