# Generated by Django 4.2.3 on 2024-06-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bitacora',
            table='bitacora',
        ),
    ]
