-- Role: "userMensajero"
-- DROP ROLE IF EXISTS "userMensajero";

CREATE ROLE "userMensajero" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:AphX73ipOViP3Md6JgJ1nA==$PrG76SMNjcA8Tq6PWStdXyh4IFA9I3q8NStuFicwOfM=:8cmO+RLgbs23Vsv3cVYmxKItxb665h79plb0GVq2cLA=';

-- Database: DBmensaje

-- DROP DATABASE IF EXISTS "DBmensaje";

CREATE DATABASE "DBmensaje"
    WITH
    OWNER = "userMensajero"
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Mexico.1252'
    LC_CTYPE = 'Spanish_Mexico.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- SCHEMA: mensajero

-- DROP SCHEMA IF EXISTS mensajero ;

CREATE SCHEMA IF NOT EXISTS mensajero
    AUTHORIZATION "userMensajero";

-- Table: mensajero.bitacora

-- DROP TABLE IF EXISTS mensajero.bitacora;

CREATE TABLE IF NOT EXISTS mensajero.bitacora
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecharegistro timestamp with time zone NOT NULL,
    mensaje_id bigint NOT NULL,
    CONSTRAINT "Bitacora_pkey" PRIMARY KEY (id),
    CONSTRAINT "Bitacora_mensaje_id_a00be5dd_fk_Mensaje_id" FOREIGN KEY (mensaje_id)
        REFERENCES mensajero.mensaje (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS mensajero.bitacora
    OWNER to "userMensajero";
-- Index: Bitacora_mensaje_id_a00be5dd

-- DROP INDEX IF EXISTS mensajero."Bitacora_mensaje_id_a00be5dd";

CREATE INDEX IF NOT EXISTS "Bitacora_mensaje_id_a00be5dd"
    ON mensajero.bitacora USING btree
    (mensaje_id ASC NULLS LAST)
    TABLESPACE pg_default;


-- Table: mensajero.catalago

-- DROP TABLE IF EXISTS mensajero.catalago;

CREATE TABLE IF NOT EXISTS mensajero.catalago
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    formatosalida character varying(100) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL,
    fecharegistro date NOT NULL,
    editable boolean NOT NULL,
    CONSTRAINT catalogo_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS mensajero.catalago
    OWNER to "userMensajero";


-- Table: mensajero.contacto

-- DROP TABLE IF EXISTS mensajero.contacto;

CREATE TABLE IF NOT EXISTS mensajero.contacto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidopaterno character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidomaterno character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecharegistro date NOT NULL,
    waid character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombreperfil character varying(100) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL,
    usuario_id bigint,
    CONSTRAINT contacto_pkey PRIMARY KEY (id),
    CONSTRAINT "contacto_usuario_id_12677780_fk_Usuario_id" FOREIGN KEY (usuario_id)
        REFERENCES mensajero.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS mensajero.contacto
    OWNER to "userMensajero";
-- Index: contacto_usuario_id_12677780

-- DROP INDEX IF EXISTS mensajero.contacto_usuario_id_12677780;

CREATE INDEX IF NOT EXISTS contacto_usuario_id_12677780
    ON mensajero.contacto USING btree
    (usuario_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: mensajero.mensaje

-- DROP TABLE IF EXISTS mensajero.mensaje;

CREATE TABLE IF NOT EXISTS mensajero.mensaje
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    wanidmensaje character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecharegistro timestamp with time zone NOT NULL,
    json text COLLATE pg_catalog."default",
    idusuario_id bigint,
    tipomensaje_id bigint,
    textomensaje character varying(10000) COLLATE pg_catalog."default" NOT NULL,
    contacto_id bigint,
    estado character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT "Mensaje_pkey" PRIMARY KEY (id),
    CONSTRAINT "Mensaje_contacto_id_0ee5558d_fk_contacto_id" FOREIGN KEY (contacto_id)
        REFERENCES mensajero.contacto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "Mensaje_idusuario_id_31dffa04_fk_Usuario_id" FOREIGN KEY (idusuario_id)
        REFERENCES mensajero.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "Mensaje_tipomensaje_id_16895a32_fk_tipoMensaje_id" FOREIGN KEY (tipomensaje_id)
        REFERENCES mensajero."tipoMensaje" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS mensajero.mensaje
    OWNER to "userMensajero";
-- Index: Mensaje_idcontacto_id_c26c1d71

-- DROP INDEX IF EXISTS mensajero."Mensaje_idcontacto_id_c26c1d71";

CREATE INDEX IF NOT EXISTS "Mensaje_idcontacto_id_c26c1d71"
    ON mensajero.mensaje USING btree
    (contacto_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: Mensaje_idusuario_id_31dffa04

-- DROP INDEX IF EXISTS mensajero."Mensaje_idusuario_id_31dffa04";

CREATE INDEX IF NOT EXISTS "Mensaje_idusuario_id_31dffa04"
    ON mensajero.mensaje USING btree
    (idusuario_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: Mensaje_tipomensaje_id_16895a32

-- DROP INDEX IF EXISTS mensajero."Mensaje_tipomensaje_id_16895a32";

CREATE INDEX IF NOT EXISTS "Mensaje_tipomensaje_id_16895a32"
    ON mensajero.mensaje USING btree
    (tipomensaje_id ASC NULLS LAST)
    TABLESPACE pg_default;



-- Table: mensajero.multimedia

-- DROP TABLE IF EXISTS mensajero.multimedia;

CREATE TABLE IF NOT EXISTS mensajero.multimedia
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    multimedia_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    archivos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Multimedia_pkey" PRIMARY KEY (id),
    CONSTRAINT "Multimedia_multimedia_id_key" UNIQUE (multimedia_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS mensajero.multimedia
    OWNER to "userMensajero";
-- Index: Multimedia_multimedia_id_d7c17aa7_like

-- DROP INDEX IF EXISTS mensajero."Multimedia_multimedia_id_d7c17aa7_like";

CREATE INDEX IF NOT EXISTS "Multimedia_multimedia_id_d7c17aa7_like"
    ON mensajero.multimedia USING btree
    (multimedia_id COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;


-- Table: mensajero.estadoMensaje

-- DROP TABLE IF EXISTS mensajero."estadoMensaje";

CREATE TABLE IF NOT EXISTS mensajero."estadoMensaje"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    formatosalida character varying(100) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL,
    fecharegistro date NOT NULL,
    editable boolean NOT NULL,
    CONSTRAINT estado_mensaje_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS mensajero."estadoMensaje"
    OWNER to "userMensajero";

-- Table: mensajero.tipoMensaje

-- DROP TABLE IF EXISTS mensajero."tipoMensaje";

CREATE TABLE IF NOT EXISTS mensajero."tipoMensaje"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    formatosalida character varying(100) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL,
    fecharegistro date NOT NULL,
    editable boolean NOT NULL,
    CONSTRAINT tipo_mensaje_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS mensajero."tipoMensaje"
    OWNER to "userMensajero";



-- Table: mensajero.usuario

-- DROP TABLE IF EXISTS mensajero.usuario;

CREATE TABLE IF NOT EXISTS mensajero.usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    usuario character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    activo smallint NOT NULL,
    fecharegistro timestamp with time zone NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    last_login timestamp with time zone NOT NULL,
    is_admin boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    is_superadmin boolean NOT NULL,
    CONSTRAINT "Usuario_pkey" PRIMARY KEY (id),
    CONSTRAINT "Usuario_email_key" UNIQUE (email),
    CONSTRAINT "Usuario_username_key" UNIQUE (username),
    CONSTRAINT "Usuario_usuario_key" UNIQUE (usuario)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS mensajero.usuario
    OWNER to "userMensajero";
-- Index: Usuario_email_013b67e0_like

-- DROP INDEX IF EXISTS mensajero."Usuario_email_013b67e0_like";

CREATE INDEX IF NOT EXISTS "Usuario_email_013b67e0_like"
    ON mensajero.usuario USING btree
    (email COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: Usuario_username_7671dc08_like

-- DROP INDEX IF EXISTS mensajero."Usuario_username_7671dc08_like";

CREATE INDEX IF NOT EXISTS "Usuario_username_7671dc08_like"
    ON mensajero.usuario USING btree
    (username COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: Usuario_usuario_511b4d9a_like

-- DROP INDEX IF EXISTS mensajero."Usuario_usuario_511b4d9a_like";

CREATE INDEX IF NOT EXISTS "Usuario_usuario_511b4d9a_like"
    ON mensajero.usuario USING btree
    (usuario COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;